/**
 * Regenerates `src/lib/preflop/rangeData.ts`, the chart dataset behind
 * `range.ts` (docs/PLAN-range-generator.md). Run with `npm run vendor-ranges`.
 *
 * Two sources:
 *   - `jensbaagaard/poker-practice` at a pinned commit: the pure ("PTO", one
 *     action per hand) files for cash 100bb and tournament 40bb. Fetched over
 *     the network, so the app build never needs it.
 *   - PokerCoaching's BTN-vs-open pack (`research/pokercoaching-btn-vs-rfi.json`),
 *     the only source that splits 3-bets into value and bluff.
 *
 * Only the action families a drill reads are kept, and identical charts are
 * stored once — the cash file reuses one chart across many seat pairs. Each
 * chart is a 169-character 0/1 string in `HAND_ORDER`.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { ALL_169 } from '../src/lib/preflop/hands.ts';

const REPO = 'jensbaagaard/poker-practice';
const COMMIT = '449993f78d995c77b72d0bcac418a8507dd6f783';
const DIR = 'data/openSourcePokerData';

/** Source id → upstream file. Adding a depth is one line here plus its `Stack` in range.ts. */
const PTO_FILES = {
  cash100: 'Cash_100_PTO.json',
  mtt40: 'MTT_40_PTO.json',
} as const;

/**
 * The key families kept: opens, facing an open (3-bet / call), and facing a
 * 3-bet (4-bet / call, plus what the 4-bet does facing a 5-bet jam, which
 * splits 4-bets into value and bluff).
 */
const KEPT = /^(Open|3Bet|Call|4Bet|Call 3Bet|Call 5Bet)[A-Z]/;

const OUT = 'src/lib/preflop/rangeData.ts';
const PC_FILE = 'research/pokercoaching-btn-vs-rfi.json';

type Chart = Record<string, number>;

function encode(chart: Chart, key: string): string {
  const missing = ALL_169.filter((hc) => !(hc in chart));
  if (missing.length) throw new Error(`${key}: missing ${missing.join(' ')}`);
  return ALL_169.map((hc) => {
    const v = chart[hc];
    if (v !== 0 && v !== 1) throw new Error(`${key} ${hc}: not pure (${v})`);
    return String(v);
  }).join('');
}

const charts: string[] = [];
const indexOf = new Map<string, number>();
function intern(bits: string): number {
  let i = indexOf.get(bits);
  if (i === undefined) {
    i = charts.length;
    charts.push(bits);
    indexOf.set(bits, i);
  }
  return i;
}

const sources: Record<string, Record<string, number>> = {};

for (const [id, file] of Object.entries(PTO_FILES)) {
  const url = `https://raw.githubusercontent.com/${REPO}/${COMMIT}/${DIR}/${file}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url}: HTTP ${res.status}`);
  const data = (await res.json()) as Record<string, Chart>;
  const keys = Object.keys(data).filter((k) => KEPT.test(k)).sort();
  sources[id] = Object.fromEntries(keys.map((k) => [k, intern(encode(data[k], `${file} ${k}`))]));
}

// PokerCoaching: one chart per opener, hand → '3bet-value' | '3bet-bluff' | 'call'.
// Split into three 0/1 charts per opener so every chart has the same shape.
const pc = JSON.parse(readFileSync(PC_FILE, 'utf8')) as { charts: Record<string, Record<string, string>> };
const PC_ACTIONS = { Value: '3bet-value', Bluff: '3bet-bluff', Call: 'call' } as const;
/** The pack names seats as the app does; store them in the PTO files' naming. */
const PC_SEAT: Record<string, string> = { UTG: 'EP1', UTG1: 'EP2', UTG2: 'EP3', LJ: 'LJ', HJ: 'HJ', CO: 'CO' };
sources.pc50 = {};
for (const [opener, chart] of Object.entries(pc.charts)) {
  if (!PC_SEAT[opener]) throw new Error(`${PC_FILE}: unknown opener ${opener}`);
  for (const hc of Object.keys(chart)) {
    if (!ALL_169.includes(hc)) throw new Error(`${PC_FILE} ${opener}: unknown hand ${hc}`);
    if (!Object.values(PC_ACTIONS).includes(chart[hc] as never)) {
      throw new Error(`${PC_FILE} ${opener} ${hc}: unknown action ${chart[hc]}`);
    }
  }
  for (const [name, action] of Object.entries(PC_ACTIONS)) {
    const bits = ALL_169.map((hc) => (chart[hc] === action ? '1' : '0')).join('');
    sources.pc50[`${name}BTNvs${PC_SEAT[opener]}`] = intern(bits);
  }
}

const keyCount = Object.values(sources).reduce((n, s) => n + Object.keys(s).length, 0);

const out = `/**
 * GENERATED by \`npm run vendor-ranges\` (scripts/vendor-ranges.ts) — do not edit.
 *
 * Sources:
 *   cash100, mtt40 — ${REPO} @ ${COMMIT.slice(0, 7)},
 *     ${DIR}/{${Object.values(PTO_FILES).join(',')}}.
 *     Scraped by that repo from a commercial trainer; licence unclear;
 *     vendored for personal use (docs/PLAN-cash.md, "Source").
 *   pc50 — ${PC_FILE} (PokerCoaching, 100bb with antes, applies ~50bb+).
 *
 * ${keyCount} keys → ${charts.length} distinct charts. Each chart is one 0/1
 * character per hand class, in \`HAND_ORDER\`. Read through \`range.ts\`.
 */

export const HAND_ORDER = '${ALL_169.join(' ')}';

export const CHARTS: readonly string[] = [
${charts.map((c) => `  '${c}',`).join('\n')}
];

export const SOURCES: Record<string, Record<string, number>> = ${JSON.stringify(sources, null, 2)
  .replace(/"([A-Za-z][A-Za-z0-9]*)":/g, '$1:')
  .replace(/"/g, "'")};
`;

writeFileSync(OUT, out);
console.log(`wrote ${OUT}: ${keyCount} keys, ${charts.length} distinct charts`);
